title: Bebashi
source: https://archive.org/download/bebashi_amfar/bebashi_amfar.mp4
homepage: true
tags:
  - activism
  - AIDS
position: 4
body:
  |
    This 17-minute video, released during the AIDS crisis, aimed to increase awareness of [HIV/AIDS](https://cnn.com) transmission pathways and encourage safe sex practices. The film focuses on an African-American single mother, who works as a nurse, and her teenage daughter who is troubled by the death of a friend’s sister due to AIDS. After an uncomfortable conversation, both mother and daughter decide to ask their respective sexual partners to use condoms. Produced by AIDSFILMS with support from Wallach and other foundations, it was directed by M. Neema Barnette and features a jazz score by Lawrence “Butch” Morris.
    — *Alberto*
captions:
  -
    start: '0:0:30'
    end: '0:0:50'
    body: Hendrerit urna a habitasse euismod dolor nec sagittis nunc fusce varius urna ullamcorper dui molestie scelerisque.
  -
    start: '0:1:45'
    end: '0:2:00'
    body: Nec nisl malesuada ad phasellus a turpis mus et adipiscing id nec consectetur gravida ac montes eu a laoreet pulvinar consectetur iaculis mi inceptos.
