title: Born Queer Dear Doctors
source: https://archive.org/download/BornQueerDearDoctors/born%20queer,%20dear%20doctors.mp4
poster: https://archive.org/download/BornQueerDearDoctors/BornQueerDearDoctors.thumbs/born%20queer,%20dear%20doctors_000001.jpg
homepage: true
position: 6
body:
  |
    *born queer, dear doctors* (2003)
    Shorona se Mbessakwini
    
    *"A love poem dedicated to the freaks, fairies, whores, sluts, genderqueers, pirates, revolutionaries, cultural (whisper it) terrorists, and just plain old punk dykes of San Francisco who are my beloved friends, family, lovers and ongoing crushes." (se Mbessakwini)*
    
    This film was made by a lover of mine at the time, Eli. It “stars” Eli, myself, and a friend of ours, Seeley. Eli and I met in the fall of 2001, soon after I had moved to San Francisco, at [Queeruption](https://www.indybay.org/newsitems/2001/09/19/1044571.php) 3: a 5-day anticapitalist gathering that included workshops, panels, performances, parties, screenings, and actions. And lots of sex. *born queer, dear doctors* reflects the Bay Area that I came up in as a young queer, which has lost much of its vitality and population due to gentrification caused by the tech boom. This five-minute film, preserved on VHS, was shot in 2002 or 2003, in Oakland, when I was twenty-two years old. I’ve been wanting to digitize it for a while, but hesitated to do so at the Graduate Center library due to the graphic nature of the content. Recently, I just threw a jacket over the screen and prayed for the best. And so, here we have it. 
    
    In the film, se Mbessakwini recites a “love letter” written to the doctor/s who assigned their gender and medically intervened upon their body without their consent as an infant who was born intersex and later as a pre-adolescent who was assigned female. The choice to accompany this text with sexual imagery was a way for se Mbessakwini to reclaim and celebrate their body and sexuality. The text has a certain spoken word quality to it—very common in the late nineties and early 2000s in some dyke circles. As well, the sexually explicit material reflects a larger trend of making and circulating queer porn—and a thriving public sexual culture more generally—that existed at that time in the Bay Area. I no longer identify as female (Eli and I both identify as trans-masculine), and my body has changed due to hormones, surgery, and age, but I am glad that this record exists, and hope that it continues to circulate and serve as a resource for intersex, queer, and trans people. Also, I had totally forgotten that I had nipple rings!
    
    Contributed by Jaime Shearn Coan 

captions:
  -
    start: '0:0:30'
    end: '0:0:50'
    body: Hendrerit urna a habitasse euismod dolor nec sagittis nunc fusce varius urna ullamcorper dui molestie scelerisque.
  -
    start: '0:1:55'
    end: '0:2:00'
    body: Nec nisl malesuada ad phasellus a turpis mus et adipiscing id nec consectetur gravid
