title: Church of Shooting Yourself
source: https://archive.org/download/ChurchofShootingYourself/ChurchofShootingYourself.mp4
poster: https://archive.org/download/ChurchofShootingYourself/ChurchofShootingYourself.thumbs/ChurchofShootingYourself_000001.jpg
homepage: true
tags:
  - activism
  - AIDS
position: 4
body:
  |
    This is a clip from a Public Access show that aired from 1993 until the early 2000s that has always haunted me — The Church of Shooting Yourself. It starred Rik Little as "Rik Arithmetic,” who filmed himself walking around the East Village holding a camcorder aimed toward his face, spouting conspiracy theories, and increasingly, as the show went on, reporting on events that he stumbled upon.
    — *Amy Herzog*
    > *Space aliens force me to think I am out of my apartment when I am in fact IN my apartment. Probably sleeping or watching television. To combat this I have taken to shooting myself almost constantly with a camcorder to prove where I am and what I do. It is a tedious job to shoot my entire life and monitor it at night (when I used to watch the evening news), so I often act like a newsman so that when I have to watch my 'daily tape' it seems more like a normal show on television. The space aliens from outer space have devious ways of splitting my brain into parts to gentrify my soul, but they will not fool me because I have television with me all the time. I will survive by shooting myself. -Rik Arithmetic (not real name/an Alias)*
captions:
  -
    start: '0:0:25'
    end: '0:0:35'
    body: Step Two
  -
    start: '0:0:40'
    end: '0:0:50'
    body: Step Three
  -
    start: '0:1:10'
    end: '0:1:40'
    body: Step Four
